### PR TITLE
Type annotations with mypy

### PR DESCRIPTION
**Pull request by geemi725**
Fix annotation errors. Address issue #16

### CODE REVIEW

**Comment by whitead** [comment]
@geemi725 can you also add a type check to the CI?

**Comment by geemi725** [comment]
Currently only errors  are:

```
exmol.py:335: error: Assignment to variable "e" outside except: block
exmol.py:336: error: Trying to read deleted variable "e"
exmol.py:353: error: Assignment to variable "e" outside except: block
exmol.py:354: error: Trying to read deleted variable "e"
exmol.py:362: error: Assignment to variable "e" outside except: block
exmol.py:363: error: Trying to read deleted variable "e"
```

But I believe this is an incorrectly marked error because variable e is used multiple times.
@whitead thoughts? [a similar issue](https://github.com/python/mypy/issues/5080)

**Comment by whitead** [comment]
@geemi725 Can you add a comment to the function to tell it to ignore those lines? That's how we usually overcome problems like this.

**Comment by whitead** [comment]
@geemi725 can you add the type annotation check to the github action tests/build files? Or tell me the command to check and I can add it.

**Comment by geemi725** [comment]
@whitead you mean `mypy <file>`?

**Comment by whitead** [comment]
@geemi725 can we remove ignores on a few of these libraries - namely numpy and itertools, which should support typing?

**Pull request merged**
