### PR TITLE
Add LIME explanations

### PR DESCRIPTION
**Pull request by hgandhi2411**
This is a big PR! 
- [x] Document LIME function
- [x] Compute t-stats using examples that have non-zero weights
- [x] Add plotting code for descriptors - needs SMARTS annotations for MACCS keys (166 files)
- [x] Add plotting code for chemical space and fit
- [x] Description in readme
- [x] Clean up notebooks and add documentation
- [x] Remove extra files
- [x] Add LIME notebooks to CI?

### CODE REVIEW

**Comment by whitead** [comment]
@hgandhi2411 for dependencies - is mordered for LIME or your trained model?

**Comment by hgandhi2411** [comment]
> @hgandhi2411 for dependencies - is mordered for LIME or your trained model?

mordred is for LIME, it's used to calculate "Classic" descriptors.

**Comment by whitead** [comment]
@hgandhi2411  see this example for loading text files in a package: https://github.com/whitead/symd/blob/c2f47c734fa1fb19ea26b7a8c740bf009097d5ba/python/symd/groups.py#L240

**Comment by whitead** [comment]
Did you add the files to be installed in your setup.py file?

**Comment by hgandhi2411** [comment]
Woohoo! All checks pass 🎉

**Comment by whitead** [comment]
@hgandhi2411 can you do the README example so I can better understand how to use it? Thank you!

**Comment by whitead** [comment]
@hgandhi2411 please update changelog and increment version and we'll be good to go

**Review by whitead — APPROVED** [review]

**Comment by whitead** [comment]
@hgandhi2411 After trying this out a bit, it's not obvious to me which descriptors match up with the return value from `lime_explain`. I understand that it should be the descriptors from the instance/base, but maybe we should return descriptors, t-statistics to avoid confusion. I don't think `beta` should be used generally because it is sensitive to units/variance.

**Comment by whitead** [comment]
@hgandhi2411 Or return nothing - since I see now those values are stored in the descriptors. Just not obvious to me how to get descriptors t-statistics as it is written now.

**Pull request merged**
